name: CI Pipeline with Liquibase and Python Tests

on:
  push:
    branches:
      - main

jobs:
  migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Шаг: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг: Ожидание готовности PostgreSQL
      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U ${{ secrets.DB_USER }}; then
              echo "Postgres is ready!";
              break;
            fi;
            echo "Waiting for Postgres...";
            sleep 5;
          done

      # Шаг: Установка зависимостей Python
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install psycopg2

      # Шаг: Запуск тестового скрипта Python
      - name: Run Python test script
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python3 src/my_project_test/test_script.py src/my_project_test/migration_script.sql

      # Шаг: Выполнение миграции через Liquibase с использованием Docker
      - name: Run Liquibase migration using Docker
        run: |
          docker run --rm \
            -v $(pwd):/liquibase/changelog \
            -e LIQUIBASE_USERNAME=${{ secrets.DB_USER }} \
            -e LIQUIBASE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e LIQUIBASE_URL=jdbc:postgresql://host.docker.internal:5432/${{ secrets.DB_NAME }} \
            -e LIQUIBASE_CHANGELOG_FILE=/liquibase/changelog/changelog.xml \
            liquibase/liquibase update
