name: CI Pipeline for PostgreSQL with SSH

on:
  push:
    branches:
      - main

jobs:
  pre_migration:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost  # Указание хоста базы данных
      DB_PORT: 5432       # Порт для подключения
      DB_USER: postgres    # Пользователь базы данных
      DB_PASSWORD: 11111   # Пароль пользователя базы данных
      DB_NAME: postgres    # Имя базы данных
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH-ключ для подключения к серверу

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip libpq-dev ssh
          pip3 install psycopg2-binary

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.8.87 >> ~/.ssh/known_hosts  # Добавление сервера в доверенные хосты

      - name: Create SSH tunnel and wait for PostgreSQL
        run: |
          ssh -N -L 5432:localhost:5432 milana@192.168.8.87 &  # Создаем туннель для подключения
          sleep 5  # Даём время на установку туннеля

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run test script
        run: |
          python3 src/my_project_test/test_connection.py
