name: CI Pipeline for Local Database

on:
  push:
    branches:
      - main

jobs:
  pre_migration:
    runs-on: ubuntu-latest

    env:  # Объявляем переменные окружения глобально для всех шагов
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_NAME: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip libpq-dev
          pip3 install psycopg2-binary

      - name: Verify connection to local database
        run: |
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "SELECT inet_server_addr(), inet_client_addr(), current_database(), current_user;"
        env:
          PGPASSWORD: $DB_PASSWORD

      - name: Run test script
        run: |
          python3 src/my_project_test/test_connection.py
