name: CI Pipeline for PostgreSQL with Docker

on:
  push:
    branches:
      - main

jobs:
  pre_migration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432  # Порт контейнера 5432 на хосте 5433
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 11111
          POSTGRES_DB: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=10

    env:
      DB_HOST: postgres  # Используйте имя сервиса вместо localhost
      DB_PORT: 5432  # Порт контейнера
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_NAME: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip libpq-dev
          pip3 install psycopg2-binary

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run test script
        run: |
          python3 src/my_project_test/test_script.py