name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  pre_migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install psycopg2

      - name: Run test script
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python3 src/my_project_test/test_script.py src/my_project_test/migration_script.sql
          
  migration:
    runs-on: ubuntu-latest
    needs: pre_migration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Liquibase migration
        uses: liquibase/liquibase-github-action@v4.23.0
        with:
          args: update
        env:
          LIQUIBASE_USERNAME: ${{ secrets.DB_USER }}
          LIQUIBASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          LIQUIBASE_URL: jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }}
          LIQUIBASE_CHANGELOG_FILE: changelog.xml

