name: CI Pipeline for PostgreSQL with Docker

on:
  push:
    branches:
      - main

jobs:
  pre_migration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest  # Используем образ PostgreSQL
        ports:
          - 5433:5433  # Открываем порт 5432 для подключения
        env:
          POSTGRES_USER: postgres  # Устанавливаем пользователя
          POSTGRES_PASSWORD: 11111  # Устанавливаем пароль
          POSTGRES_DB: postgres  # Устанавливаем имя базы данных
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_NAME: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip libpq-dev
          pip3 install psycopg2-binary

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run test script
        run: |
          python3 src/my_project_test/test_script.py