name: CI Pipeline with Liquibase and Python Tests

on:
  push:
    branches:
      - main

jobs:
  migration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Шаг: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг: Ожидание готовности PostgreSQL
      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "Postgres is ready!";
              break;
            fi;
            echo "Waiting for Postgres...";
            sleep 5;
          done

      # Шаг: Установка зависимостей Python
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install psycopg2

      # Шаг: Запуск тестового скрипта Python
      - name: Run Python test script
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python3 src/my_project_test/test_script.py src/my_project_test/migration_script.sql

      # Шаг: Выполнение миграции через Liquibase с использованием Docker
      - name: Run Liquibase migration using Docker
        env:
          LIQUIBASE_USERNAME: ${{ secrets.DB_USER }}
          LIQUIBASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          LIQUIBASE_URL: jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }}
        run: |
          docker run --rm \
            -v $(pwd)/my_project_test:/liquibase/changelog \
            -e LIQUIBASE_USERNAME=$LIQUIBASE_USERNAME \
            -e LIQUIBASE_PASSWORD=$LIQUIBASE_PASSWORD \
            -e LIQUIBASE_URL=$LIQUIBASE_URL \
            liquibase/liquibase \
            --url=$LIQUIBASE_URL \
            --username=$LIQUIBASE_USERNAME \
            --password=$LIQUIBASE_PASSWORD \
            --changeLogFile=/liquibase/changelog/example-changelog.sql update
