  stages:
      - test

  services:
      - postgres:latest

  variables:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_NAME: postgres

  test_connection:
      stage: test
      before_script:
        - pip install psycopg2
        - until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do echo "Waiting for PostgreSQL..."; sleep 2; done
      script:
        - python3 src/my_project_test/test_connection.py
