name: CI Pipeline for PostgreSQL without Docker

on:
  push:
    branches:
      - main

jobs:
  pre_migration:
    runs-on: ubuntu-latest  # Используем стандартный Ubuntu агент

    env:  # Объявляем переменные окружения глобально для всех шагов
      DB_HOST: localhost
      DB_PORT: 5433  # Указываем порт PostgreSQL, который у вас настроен
      DB_USER: postgres
      DB_PASSWORD: 11111
      DB_NAME: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip libpq-dev
          pip3 install psycopg2-binary

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run test script
        run: |
          python3 src/my_project_test/test_script.py
