stages:
  - pre-migration - migration
pre_migration:
  stage: pre-migration
  image: python:3.9
  script:
    - pip install psycopg2
    - python src/my_project_test/test_script.py
      src/my_project_test/migration_script.sql
  only:
    - main
migration:
  stage: migration
  image: liquibase/liquibase:latest
  script:
    - liquibase update
  only:
    - main